runtime: nodejs16

env_variables:
  APP_BACKEND_URL: "https://backend-dot-for-fun-153903.uc.r.appspot.com"

handlers:
- url: /static
  static_dir: build/static

- url: /(.*\.(json|ico|js))$
  static_files: build/\1
  upload: build/.*\.(json|ico|js)$

- url: /(.+\..+)$
  static_files: build/\1
  upload: build/.+\..+$

- url: .*
  static_files: build/index.html
  upload: build/index\.html