service: backend
runtime: nodejs20
entrypoint: node dist/index.js

handlers:
  - url: /.*
    script: auto

env_variables:
  GOOGLE_PROJECT_ID: 'for-fun-153903'
  FRONTEND_URL: 'https://for-fun-153903.uc.r.appspot.com'
  BACKEND_URL: 'https://backend-dot-for-fun-153903.uc.r.appspot.com'